USE_CAMERA_STUB := true

# inherit from the proprietary version
-include vendor/moto/panelli/BoardConfigVendor.mk

#Platform
TARGET_ARCH := arm
TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := mt6737m
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_VARIANT := cortex-a53
TARGET_CPU_SMP := true
ARCH_ARM_HAVE_TLS_REGISTER := true

TARGET_BOOTLOADER_BOARD_NAME := mt6737m

#kernel
BOARD_KERNEL_CMDLINE := bootopt=64S3,32N2,32N2 androidboot.selinux=disabled
BOARD_KERNEL_BASE := 0x40000000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_RAMDISK_OFFSET := 0x04000000
BOARD_TAGS_OFFSET := 0xE000000
TARGET_KERNEL_ARCH := arm
TARGET_KERNEL_CONFIG := panelli_defconfig
BOARD_KERNEL_IMAGE_NAME := zImage-dtb
TARGET_KERNEL_SOURCE := kernel/moto/panelli
BOARD_MKBOOTIMG_ARGS := --kernel_offset $(BOARD_KERNEL_OFFSET) --ramdisk_offset $(BOARD_RAMDISK_OFFSET) --tags_offset $(BOARD_TAGS_OFFSET)

# fix this up by examining /proc/mtd on a running device
BOARD_BOOTIMAGE_PARTITION_SIZE := 16777216
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 16777216
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 2432696320
BOARD_USERDATAIMAGE_PARTITION_SIZE := 4698144768
BOARD_FLASH_BLOCK_SIZE := 131072

BOARD_HAS_NO_SELECT_BUTTON := true


#Audio
BOARD_USES_MTK_AUDIO := true
MTK_HIGH_RESOLUTION_AUDIO_SUPPORT := true
AUDIO_POLICY_TEST := true
MTK_DIGITAL_MIC_SUPPORT := true
MTK_FM_SUPPORT := true
MTK_VOIP_ENHANCEMENT_SUPPORT := true
MTK_EMULATOR_SUPPORT := yes
MTK_USE_ANDROID_MM_DEFAULT_CODE := true
MTK_HAC_SUPPORT := true
MTK_BSP_PACKAGE := true
MTK_FM_SUPPORT := true
MTK_FM_TX_SUPPORT := true
MTK_FM_TX_AUDIO := FM_DIGITAL_OUTPUT
BOARD_HAVE_BLUETOOTH := true
HAVE_SRSAUDIOEFFECT_FEATURE := true
MTK_AUDIO_HD_REC_SUPPORT := true
MTK_VOIP_ENHANCEMENT_SUPPORT := true
MTK_HANDSFREE_DMNR_SUPPORT := true
NATIVE_AUDIO_PREPROCESS_ENABLE := true



#HW
MTK_HWC_SUPPORT := true
MTK_HWC_VERSION := 1.4
MTK_ROTATION_OFFSET_SUPPORT := true


#Graphics
MTK_GPU_VERSION := mali


#Sensor
MTK_SENSORS_1_0 := true

#Camera
MTK_EMULATOR_SUPPORT := true

# Lineage Hardware
BOARD_HARDWARE_CLASS += device/moto/panelli/lineagehw


#Wifi
MTK_BASIC_PACKAGE := true
MTK_WLAN_SUPPORT := true
BOARD_WLAN_DEVICE := MediaTek
WPA_SUPPLICANT_VERSION := VER_0_8_X
BOARD_HOSTAPD_DRIVER := NL80211
BOARD_HOSTAPD_PRIVATE_LIB := lib_driver_cmd_mt66xx
BOARD_WPA_SUPPLICANT_DRIVER := NL80211
BOARD_WPA_SUPPLICANT_PRIVATE_LIB := lib_driver_cmd_mt66xx
WIFI_DRIVER_FW_PATH_PARAM := /dev/wmtWifi
WIFI_DRIVER_FW_PATH_AP := AP
WIFI_DRIVER_FW_PATH_STA := STA
WIFI_DRIVER_FW_PATH_P2P := P2P
WIFI_DRIVER_STATE_CTRL_PARAM := /dev/wmtWifi
WIFI_DRIVER_STATE_ON := 1
WIFI_DRIVER_STATE_OFF := 0



# Recovery
BOARD_HAS_DOWNLOAD_MODE := true
TARGET_RECOVERY_PIXEL_FORMAT := "RGBX_8888"
TARGET_RECOVERY_FSTAB := device/panelli/ramdisk/recovery.fstab
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
